# Generated by Django 2.2.5 on 2019-09-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='film_name',
            field=models.CharField(max_length=50),
        ),
    ]
