# Generated by Django 2.2.5 on 2019-09-20 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_film_film_runtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='film_runtime',
        ),
    ]
