# Generated by Django 2.2.5 on 2019-09-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20190920_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='director_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='imdb_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='movie_runtime',
            field=models.IntegerField(null=True),
        ),
    ]
