# Generated by Django 2.2.5 on 2019-09-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20190928_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='movie_runtime',
            field=models.IntegerField(null=True),
        ),
    ]
