# Generated by Django 2.2.5 on 2019-09-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20190928_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='release_date',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
