# Generated by Django 2.2.6 on 2019-10-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20190928_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='movie_poster',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
