# Generated by Django 2.2.6 on 2019-10-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_film_movie_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='poster',
            field=models.ImageField(blank=True, height_field=250, null=True, upload_to='media/posters/', width_field=250),
        ),
    ]
